### ISSUE TITLE
Issue with 'xconn' Package: "Target of URI doesn't exist" in Flutter Project

### ISSUE THREAD

**Issue by asimfarooq5** [xconnio/xconn-dart#61]
#### Description:

I am encountering an issue with the xconn package in my Flutter project. When trying to import the xconn package, I receive the following error:
```
Target of URI doesn't exist: 'package:xconn/xconn.dart'. (Documentation)
```
#### Steps to Reproduce:

Add xconn dependency to pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter
  xconn: ^0.1.0
  ```
Run flutter pub get to fetch dependencies.

Attempt to import the package in a Dart file:

```
import 'package:xconn/xconn.dart';
```
#### Expected Behavior:

The xconn package should be imported without any issues.

#### Actual Behavior:

The following error is shown:

```
Target of URI doesn't exist: 'package:xconn/xconn.dart'. (Documentation)
```

#### Environment Details:

Flutter version: 3.24.5

Dart version: 3.5.4

xconn package version: ^0.1.0

Operating System: Ubuntu 24.04.1 LTS

Additional Information:

I have confirmed that the xconn package is listed as a dependency in the pubspec.yaml file and have run flutter pub get without any errors. It seems like the package might not be correctly installed or available. I would appreciate any guidance on resolving this issue.

**Comment by muzzammilshahid** [comment]
Try importing `package:xconn/exports.dart;`
